"""empty message

Revision ID: 2e318ae58342
Revises: bec660f9f16c
Create Date: 2024-10-02 22:17:09.625637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e318ae58342'
down_revision = 'bec660f9f16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('education')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
