"""empty message

Revision ID: 4fba115a97c0
Revises: e982f31fddf1
Create Date: 2024-10-02 19:22:14.101256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fba115a97c0'
down_revision = 'e982f31fddf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=True),
    sa.Column('minval', sa.Integer(), nullable=True),
    sa.Column('maxval', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_options')
    # ### end Alembic commands ###
