"""empty message

Revision ID: 85c1ae6d2cb9
Revises: 609b51fd94ac
Create Date: 2024-10-09 10:43:04.173952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c1ae6d2cb9'
down_revision = '609b51fd94ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attribute_category', sa.String(), nullable=False),
    sa.Column('attribute_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_attributes_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('gender')
        batch_op.drop_column('height')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))

    op.drop_table('user_attributes')
    # ### end Alembic commands ###
