"""initial migrate

Revision ID: c334dcae17b5
Revises: 
Create Date: 2024-09-27 13:21:39.356921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c334dcae17b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matcher_id', sa.Integer(), nullable=False),
    sa.Column('matchee_id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchee_id'], ['users.id'], name=op.f('fk_likes_matchee_id_users')),
    sa.ForeignKeyConstraint(['matcher_id'], ['users.id'], name=op.f('fk_likes_matcher_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matcher_id', sa.Integer(), nullable=False),
    sa.Column('matchee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchee_id'], ['users.id'], name=op.f('fk_matches_matchee_id_users')),
    sa.ForeignKeyConstraint(['matcher_id'], ['users.id'], name=op.f('fk_matches_matcher_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pref_category', sa.String(), nullable=False),
    sa.Column('pref_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    op.drop_table('matches')
    op.drop_table('likes')
    op.drop_table('users')
    # ### end Alembic commands ###
