"""empty message

Revision ID: c7553bc1c978
Revises: 85c1ae6d2cb9
Create Date: 2024-10-10 13:57:24.155661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7553bc1c978'
down_revision = '85c1ae6d2cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
